services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
      - JELLYFIN_PublishedServerUrl=http://${IP}
    volumes:
      - ./config/jellyfin/config:/config
      - ./data/media/tv:/data/tvshows
      - ./data/media/movies:/data/movies
      - ./mnt/torrents:/mnt/torrents
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"  # Radarr web interface
    volumes:
      - ./config/radarr/config:/config  # Radarr configuration files
      - ./data:/data
      - ./mnt/torrents:/mnt/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"  # Sonarr web interface
    volumes:
      - ./config/sonarr/config:/config  # Sonarr configuration files
      - ./data:/data
      - ./mnt/torrents:/mnt/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Dublin
      - AUTO_UPDATE=true
    volumes:
      - ./config/jackett:/config
      - ./data/indexing-jackett:/downloads
      - ./mnt/torrents:/mnt/torrents
    ports:
      - 9117:9117

  deluge:
    image: lscr.io/linuxserver/deluge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Dublin
    volumes:
      - ./config/deluge:/config
      - ./data:/data
      - ./mnt/torrents:/mnt/torrents
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp